language: cpp
compiler:
- clang
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install cmake
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
  - curl -T ip_filter-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb -ultaa:${BINTRAYKEY} "https://api.bintray.com/content/ltaa/hello/otus_hello/0.0.${TRAVIS_BUILD_NUMBER}/ip_filter-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
env:
  global:
    secure: lCZZ36qNngyf5vHzDl1qgbt7M2jFIGXQv4/WZ0GOsxZlwJjk0d6pYQOFs+RAant5rzDJZqk2jDs63kzXbQ/tXw7MBQfoClOFUpx5Brxghf4NjJeEFhUwp9zsRcO6RORdmlG6Hnd8GZwNUIZ5RrG/a3koZ1Ot5MLyyqwICaPtr8ATYoN56c9EvSHP3XG9M1tB3foUWDNyD86+srkooFbnfxIhjnvBDxf/pvgUwWY/s+a4UDbu+SISjsZG2s1qQTMIfn894YjdyQP9k6lVeqbyCiPp8MUDf3YJsS2tQ+PfcbNMJBp7yBwMSzFSmj+jxNh/xEKkvsK9bD4tsxvw6/UNYLOi7GRs8Hdt4Tvhc1Ot6sgYs5do3GuJy7p0YxAAOj6tu4n1IA+n4YudGzEyrn04YJNjclgt+qvLrKu83E67N016sHFK25aVqH4z86m05vIQCQx4QcSLBNrLYU+Y0/0BCqw89GaWMZgepQVbUyC2MBLu+kzjk623uGDrc7inQVRuyhE473DgLHnMwSFJsy8X2L/WSJgP4AK4prz3M60rsYUVHBCZi+TDuh/6O7Be5icDbMDXEm8KqGDSZamfG7RE2r9xitvzit6XeYIZzPyMLAN1lXVUgZWcvj5YjnMQds0OxYEe96okBF2Jj5V5BK/S0BGNavPYAxQeO3B5Uo2Rqc8=

