language: cpp
compiler:
- clang
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install cmake
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  on:
    all_branches: true
  script:
  - curl -T ip_filter-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb -ultaa:${BINTRAYKEY} "https://api.bintray.com/content/ltaa/hello/otus_hello/0.0.${TRAVIS_BUILD_NUMBER}/ip_filter-0.0.${TRAVIS_BUILD_NUMBER}-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
env:
  global:
    secure: wGGqfZhlFBrm0dxzZyYQwxAgLT20CqEwdjJcKAJGbhoSBqPOEFb37LyBJyCcjTHE+So1rBD6kM2RGODndbXBd/cRbEX02NFeIrOBYj6bCYFwKg7Bp/LYxbbT55X2LDsGm3/gd00bEnBqAXswwDMKpdxCTXdIGEljfy24mkchP8BG9ZUhBKetSMJDhOZrdgPZBNoUSD03g4w/t3YG0RKTiUOxMke2Wf8//xuMAEc7m2H0RbHF2TR20DuXt6er7M0gsvbNi2rvv7w6JKMinkJdNLwRawetqFORLKauoULgnxQiMLOWDfq8IGpB+OChWeLdVvxPwGbpx26LIP5FUk2Wco/gzSo/43dq8M15pJk3hBZmklqvbN+L4vnzY6vQaCryf5It/FvHdZUZq4CHdWScC3W2n99nBaSk1TEiKBN2mFTX1u5bh+vcHsW6TOvaZp/WQMKH7xdsQohABsByVEnsMKZz9BWRz+/Y5PMBM0RIkKn8hOKAPmi3lGphkhKiou73XickpGs81T37bLiEZd5dq8JxzGCSG8urBaeT9KkKmQCvLfl2rJ/WY7MHFR/Qu0jNOz2WqY8AxhUrONVvOjr/koXKfs3JlibjmgspXvvF8C6RyZ41kMt99V6nNa0bu4i25P2LY/IIRqeEuwP/49lq28e6+vb+op0ecxDpAmO+zDM=

